# Generated by Django 5.2.7 on 2025-10-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('in_nifty50', models.BooleanField(default=False)),
            ],
        ),
    ]
